### ISSUE TITLE
Asker does not send query on node 0.11.14

### ISSUE THREAD

**Issue by golyshevd** [nodules/asker#98] opened 2014-12-07 15:02 UTC
The issue in breaking changes in node's ```url``` module
```js
// 0.10.33
url.parse('/', true).query // {}

// 0.11.14
url.parse('/', true).query // null
```
[Here](https://github.com/nodules/asker/blob/master/lib/asker.js#L125) you get ```null``` if ```path``` option did not contain querysrting but ```query``` option is object

**Comment by narqo** [comment] 2015-09-20 20:17
Looks like everything work as expected in both nodejs-0.12 and nodejs-4:

~~~js
› 0.12/bin/node --version
v0.12.4
› 0.12/bin/node -p "require('url').parse('/', true).query"
{}

› 4/bin/node --version
v4.1.0
› 4/bin/node -p "require('url').parse('/', true).query"
{}
~~~

Guess the issue is out of date now.

**Comment by narqo** [comment] 2015-11-10 13:30
Closing as "can't reproduce".

**Closed by narqo** 2015-11-10 13:30 UTC
Labels: 0.12, bug, critical
